[package]
name = "small-ecs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
